#
# fmt
#
[fmt.package]
name = "fmt"

[fmt.dependencies]
default = { git = "https://github.com/fmtlib/fmt", tag = "{version}" }

[fmt.targets]
default = { src = ["{default}/src/format.cc", "{default}/src/os.cc"], inc = ["public:{default}/include"] }

#
# spdlog
#
[spdlog.package]
name = "spdlog"

[spdlog.dependencies]
default = { git = "https://github.com/gabime/spdlog", tag = "v{version}" }

[spdlog.targets]
default = { src = ["{default}/src/*"], inc = ["public:{default}/include"], flags = ["public:-DSPDLOG_FMT_EXTERNAL"] }
fmt = { src = ["{default}/src/*"], inc = ["public:{default}/include"] }


#
# nlohmann_json
#
[nlohmann_json.package]
name = "nlohmann_json"

[nlohmann_json.dependencies]
default = { path = "https://github.com/nlohmann/json/releases/download/v{version}/json.tar.xz" }


#
# yyjson
#
[yyjson.package]
name = "yyjson"

[yyjson.dependencies]
default = { git = "https://github.com/ibireme/yyjson", tag = "{version}" }

[yyjson.targets]
default = { src = ["{default}/src/yyjson.c"], inc = ["{default}/src"] }


#
# rapidjson
#
[rapidjson.package]
name = "rapidjson"

[rapidjson.dependencies]
default = { git = "https://github.com/Tencent/rapidjson", tag = "v{version}" }


#
# toml++
#
['toml++'.package]
name = "toml++"

['toml++'.dependencies]
default = { git = "https://github.com/marzer/tomlplusplus", tag = "v{version}" }


#
# yaml-cpp
#
[yaml-cpp.package]
name = "yaml-cpp"

[yaml-cpp.dependencies]
default = { git = "https://github.com/jbeder/yaml-cpp", tag = "yaml-cpp-{version}" }


#
# Boost.PFR
#
[pfr.package]
name = "pfr"

[pfr.dependencies]
default = { git = "https://github.com/boostorg/pfr", tag = "boost-{version}" }


#
# Magic Enum
#
[magic_enum.package]
name = "magic_enum"

[magic_enum.dependencies]
default = { git = "https://github.com/Neargye/magic_enum", tag = "v{version}" }


#
# CLI11
#
[CLI11.package]
name = "CLI11"

[CLI11.dependencies]
default = { git = "https://github.com/CLIUtils/CLI11", tag = "v{version}" }


#
# cpp-httplib
#
[httplib.package]
name = "httplib"

[httplib.dependencies]
default = { git = "https://github.com/yhirose/cpp-httplib", tag = "v{version}" }

[httplib.targets]
default = { inc = ["public:{default}"], link-flags = ["-lpthread"] }
ssl = { flags = ["public:-DCPPHTTPLIB_OPENSSL_SUPPORT"], link-flags = ["-lssl", "-lcrypto"] }
zlib = { flags = ["public:-DCPPHTTPLIB_ZLIB_SUPPORT"], link-flags = ["-lz"] }


#
# sha256
#
[sha256.package]
name = "sha256"

[sha256.dependencies]
default = { git = "https://github.com/LekKit/sha256", branch = "{version}" }

[sha256.targets]
default = { src = ["{default}/sha256.c"], inc = ["public:{default}"] }


#
# gtest
#
[gtest.package]
name = "gtest"

[gtest.dependencies]
default = { path = "https://github.com/google/googletest/releases/download/v{version}/googletest-{version}.tar.gz" }

[gtest.targets.default]
src = ["{default}/googletest/src/gtest-all.cc"]
inc = ["public:{default}/googletest/include", "{default}/googletest"]

[gtest.targets.'gtest-main']
src = ["{default}/googletest/src/gtest-all.cc", "{default}/googletest/src/gtest_main.cc"]
inc = ["public:{default}/googletest/include", "{default}/googletest"]


#
# onnxruntime
#
[onnx.package]
name = "onnx"

[onnx.dependencies]
default = { path = "https://github.com/microsoft/onnxruntime/releases/download/v{version}/onnxruntime-linux-x64-{version}.tgz" }
gpu = { path = "https://github.com/microsoft/onnxruntime/releases/download/v{version}/onnxruntime-linux-x64-gpu-{version}.tgz", optional = true }

[onnx.targets]
default = { link-flags = ["{default}/lib/libonnxruntime.so"], inc = ["public:{default}/include"] }
gpu = { link-flags = ["{gpu}/lib/libonnxruntime.so"], inc = ["public:{gpu}/include"] }


#
# catch2
#
[catch2.package]
name = "catch2"
edition = 14

[catch2.dependencies]
default = { git = "https://github.com/catchorg/Catch2", tag = "v{version}" }

[catch2.targets.default]
src = [
    "{default}/src/catch2/*.cpp",
    "{default}/src/catch2/benchmark/*.cpp",
    "{default}/src/catch2/benchmark/detail/*.cpp",
    "{default}/src/catch2/generators/*.cpp",
    "{default}/src/catch2/interfaces/*.cpp",
    "{default}/src/catch2/internal/*.cpp",
    "{default}/src/catch2/matchers/*.cpp",
    "{default}/src/catch2/matchers/internal/*.cpp",
    "{default}/src/catch2/reporters/*.cpp",
]
inc = ["public:{default}/src"]


#
# ftxui
#
[ftxui.package]
name = "ftxui"

[ftxui.dependencies]
default = { git = "http://github.com/ArthurSonzogni/FTXUI", tag = "v{version}" }

[ftxui.targets]
screen = { src = ["{default}/src/screen/*.cpp"], inc = ["public:{default}/include"] }
dom = { src = ["{default}/src/dom/*.cpp"], inc = ["public:{default}/include"] }
component = { src = ["{default}/src/component/*.cpp"], inc = ["public:{default}/include"] }

[ftxui.features]
default = ["screen", "dom", "component"]


#
# async_simple
#
[async_simple.package]
name = "async_simple"
edition = 20

[async_simple.dependencies]
default = { git = "https://github.com/alibaba/async_simple", tag = "v{version}"}

[async_simple.targets]
default = { inc = ["public:{default}"] }


#
# cpptrace
#
[cpptrace.package]
name = "cpptrace"

[cpptrace.dependencies]
default = { git = "https://github.com/jeremy-rifkin/cpptrace", tag = "v{version}" }

[cpptrace.targets.default]
src = [
    "{default}/src/*.cpp",
    "{default}/src/binary/*.cpp",
    "{default}/src/demangle/*.cpp",
    "{default}/src/jit/*.cpp",
    "{default}/src/platform/*.cpp",
    "{default}/src/snippets/*.cpp",
    "{default}/src/symbols/*.cpp",
    "{default}/src/unwind/*.cpp",
    "{default}/src/utils/*.cpp",
    "{default}/src/utils/io/*.cpp",
]
inc = ["public:{default}/include"]
